[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false


### 13.2 Update .gitignore

**Edit `.gitignore`:**

# Python
venv/
__pycache__/
*.pyc
*.pyo
*.pyd
.Python
*.so

# Environment
.env
.venv

# Data
data/*.csv
data/*.xlsx
outputs/

# IDE
.vscode/
.idea/
*.swp
*.swo
*~

# OS
.DS_Store
Thumbs.db

# Streamlit
.streamlit/secrets.toml

# Jupyter
.ipynb_checkpoints/
*.ipynb

# Misc
*.log